language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt coverage pytest
# command to run tests
script: coverage run unit_tests.py
after_success:
  - bash <(curl -s https://codecov.io/bash)