# NOTE: not used
{% set data = load_setup_py_data() %}

package:
  name: gbdx-auth
  version: {{ data.get('version') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script: pip install .
  noarch: python

source:
  git_url: ./

requirements:
  run:
    - python
    - requests >=2.18.4
    - oauthlib >=2.0.2
    - requests-oauthlib >=0.8.0
    - pyjwt >=1.4.2
    - future >=0.16.0
    - configparser >=3.5.0

  build:
    - setuptools
    - python {{ python }}
    - requests >=2.18.4
    - oauthlib >=2.0.2
    - requests-oauthlib >=0.8.0
    - pyjwt >=1.4.2
    - future >=0.16.0
    - configparser >=3.5.0
